### ISSUE TITLE
Come on who the fuck gonna click on allow!

### ISSUE THREAD

**Issue by minanagehsalalma** [Abhi6722/grabcam#1]

**Comment by Abhi6722** [comment]
Then what the fuck do expect....

It is mobile based tool which is providing you this much features.....
If you are not satisfied you can try other tools

**Comment by minanagehsalalma** [comment]
> It is mobile based tool which is providing you this much features.....

@Abhi6722 
It doesn't matter the problem is with the idea of the tool.


> you can try other tools

There isn't... the permission ask pop up  is made for a reason.

**Comment by Prosanna69** [comment]
lmao
