### ISSUE TITLE
Excellent work my friend

### ISSUE THREAD

**Issue by petkakisgeorge** [Abhi6722/grabcam#2]
Do you mind if i use your code to create my own script? 
Probably run it in my server to avoid serveo cause fb detects it but still very good. I will refer to you of course.

**Comment by Abhi6722** [comment]
You are free to use it brother and if you want detail instructions then you can check my video Tutorial and blog also...

Videl Tutorial
https://youtu.be/eAUoKI-YVq8

Detail process
https://hackers-hub.com/grabcam
